#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ln1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ln2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ln3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ln4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int lncover = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mn1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mn10 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mn11 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mn12 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int mn2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mn3 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int mn4 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mn5 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int mn6 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int mn7 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int mn8 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int mn9 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int mncover = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int t1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int t2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int t3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int t4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int t5 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int t6 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int t7 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tcover150 = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int imgbtnLN = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int imgbtnMN = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int imgbtnT = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ViewAlbum = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
